const tc = {
  langSetting:'語言設定',
  open: '打開',
  close: '關閉',
  determin: '確定',
  save: '保存',
  saveAs: '另存',
  add: '新增',
  clean: '清除',
  insert: '插入',
  delete: '刪除',
  event: '事件',
  detail: '詳細',
  gear:'檔位',
  id: 'ID',
  content: 'Content',
  describe: '物件描述',
  gameTemp: '遊戲模板',
  overAll: '全局',
  mainGame: '主遊戲',
  freeSpin: 'FreeSpin',
  emulator: '模擬器',
  please_select_profile: '請選擇設定檔',
  bet_multiple: '投注倍數',
  basic_bet: '基礎投注',
  bet_size: '投注大小',
  bet_amount: '投注額',
  type: 'Type',
  spin_bonus_multiplier: '旋轉獎金乘倍',
  multiply: '乘倍',
  roller: '滾輪',
  object: '物件',
  resistance: '阻值',
  number_of_entries: '輸入次數',
  single_gear: '單檔',
  reality: '真實',
  mode_of_operation: '運作方式',
  number_of_lines: '線數',
  place_bet: '下注',
  output_log: '輸出日誌',
  start_calculation: '開始演算',
  mtrp: 'MRTP',
  revenue_settlement: '收益結算',
  tax_amount: '稅收金額',
  number_of_earnings: '收益次數',
  rate_of_return: '收益率',
  total_revenue_times: '總收益次數',
  total_return: '總收益率',
  total: '共計',
  round: '回',
  rounds: '輪次',
  frequency: '次',
  cumulative_income: '累計收益',
  trtp: 'TRTP',
  total_revenue: '總收益',
  freeSpin_game_highest_earnings: 'FreeSpin遊戲最高收益',
  highest_profit_in_a_single: '單次最高收益',
  maximum_single_basic_income: '單次最高基礎收益',
  highest_total_revenue_per_time: '單次總收益最高收益',
  number_of_times_won: '中獎次數',
  odds_of_winning: '中獎率',
  please_choose: '請選擇',
  message_window: '訊息視窗',
  start_time: '開始時間',
  total_time_spent: '總共耗時',
  line_coefficient: '線係數',
  explanation_of_line_coefficients: '單線底注=基礎底注/線係數',
  bonus_denominator: '獎金分母',
  please_select_template: '請選擇模板',
  wrong_profile_selection:'設定檔選擇錯誤',
  gold_appearance_rate:'黃金出現率',
  quantity:'數量',
  weights:'權重',
  please_click_on_the_shaft_component_first:'請先點選軸帶元件',
  thread:'線程',
  please_enter_the_bet_amount_first:'請先輸入投注額',
  please_enter_the_number_of_rounds_first:'請先輸入回合數',
  please_select_the_Log_path_first:'請先選擇Log路徑',
  gold_turns_wild:'黃金變wild'
}

module.exports = {
  Lang: {
    tc: tc
  },
  MenuTxt: {
    tc: {
      setting: '設定',
      contact_us: '聯繫我們',
      edit:'編輯'
    },
    sc: {
      setting: '设置',
      contact_us: '联系我们',
      edit:'编辑'
    }
  },
  Support:{
    tc:'繁體中文',
    sc:'简体中文'
  }
}
